version: 2.1

executors:
  maven-executor:
    docker:
      - image: openjdk:20-jdk-bullseye
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout

      - run:
          name: Update and Install Basic Dependencies
          command: |
            apt-get update
            apt-get install -y wget curl unzip --fix-missing

      - run:
          name: Install Additional Dependencies - Group 1
          command: |
            apt-get install -y libgbm1 libnspr4 --fix-missing

      - run:
          name: Install Additional Dependencies - Group 2
          command: |
            apt-get install -y libnss3 libu2f-udev libvulkan1 --fix-missing

      - run:
          name: Install Additional Dependencies - Group 3
          command: |
            apt-get install -y xdg-utils fonts-liberation --fix-missing

      - run:
          name: Install Maven
          command: |
            MAVEN_VERSION=3.3.1
            echo "Downloading Maven version ${MAVEN_VERSION}"
            curl -f -o /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
            
            # Check if the download was successful
            if [ ! -f /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz ]; then
              echo "Download failed or file not found!"
              exit 1
            fi
            
            # Print first few lines to check content (optional for debugging)
            head -n 20 /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz

            # Extract Maven
            tar xzvf /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt/ || {
              echo "Failed to extract Maven. Exiting."
              exit 1
            }

            ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/local/bin/mvn
            rm /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz

      - run:
          name: Install Chrome
          command: |
            curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /tmp/google-chrome-stable_current_amd64.deb
            apt-get update
            apt-get install -y /tmp/google-chrome-stable_current_amd64.deb
            rm /tmp/google-chrome-stable_current_amd64.deb

      - run:
          name: Install ChromeDriver
          command: |
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
            curl -sSL "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -o chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            mv chromedriver /usr/local/bin/chromedriver
            chmod +x /usr/local/bin/chromedriver

      - run:
          name: Install Maven Dependencies
          command: mvn install -DskipTests

      - run:
          name: Run Tests
          command: mvn clean test

      - run:
          name: Generate Allure Report
          command: mvn allure:report

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
