# CircleCI configuration
version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:20.0-browsers
    working_directory: ~/repo
    environment:
      TEST_ENV: prod

jobs:
  test:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Display environment details
          command: |
            echo "User: $(whoami)"
            echo "Java Version: $(java -version)"
            echo "Maven Version: $(mvn -version)"
            echo "Chrome Version: $(google-chrome --version)"
            echo "ChromeDriver Version: $(chromedriver --version)"

      # Install dependencies
      - run:
          name: Install Maven Dependencies
          command: mvn dependency:go-offline

      # Run tests with screenshots and debugging
      - run:
          name: Run Tests
          command: |
            mvn test -Dsurefire.suiteXmlFiles= testngFiles/testng.xml \
            -Dbrowser=chrome -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver

      # Store screenshots as artifacts
      - store_artifacts:
          path: target/screenshots
          destination: screenshots

      # Store test results
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  commit_workflow:
    jobs:
      - test

  scheduled_workflow:
    triggers:
      - schedule:
          cron: "55 10 * * *"  # Runs daily at 10 05 UTC
          filters:
            branches:
              only:
                - main
    jobs:
      - test
