version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:20-bullseye
    working_directory: ~/repo

jobs:
  test:
    executor: java-executor
    steps:
      - checkout

      # Cache dependencies to speed up builds
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      # Install dependencies
      - run:
          name: Install Maven Dependencies
          command: mvn dependency:go-offline

      # Save dependencies to cache
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Run tests
      - run:
          name: Run Tests
          command: mvn test -Dsurefire.suiteXmlFiles=src/main/resources/testng1.xml

      # Store test results
      - store_test_results:
          path: target/surefire-reports

      # Store artifacts (optional)
      - store_artifacts:
          path: target
          destination: artifacts

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
