version: 2.1

executors:
  maven-executor:
    docker:
      - image: openjdk:20-jdk-bullseye
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y \
              wget \
              curl \
              unzip \
              libgbm1 \
              libnspr4 \
              libnss3 \
              libu2f-udev \
              libvulkan1 \
              xdg-utils \
              fonts-liberation \
              --fix-missing

      - run:
          name: Install Chrome
          command: |
            curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome-stable_current_amd64.deb
            apt-get update
            apt-get install -y ./google-chrome-stable_current_amd64.deb

      - run:
          name: Install ChromeDriver
          command: |
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
            curl -sSL "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -o chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            mv chromedriver /usr/local/bin/chromedriver
            chmod +x /usr/local/bin/chromedriver

      - run:
          name: Install Maven Dependencies
          command: mvn install -DskipTests

      - run:
          name: Run Tests
          command: mvn clean test

      - run:
          name: Generate Allure Report
          command: mvn allure:report

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
