version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:11.0
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout

      - run:
          name: Install Maven Dependencies
          command: mvn install -DskipTests

      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser

      - run:
          name: Install ChromeDriver
          command: |
            CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
            unzip ~/chromedriver_linux64.zip -d ~/
            rm ~/chromedriver_linux64.zip
            sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
            sudo chown root:root /usr/local/bin/chromedriver
            sudo chmod 0755 /usr/local/bin/chromedriver

      - run:
          name: Run Tests
          command: mvn clean test

      - run:
          name: Generate Allure Report
          command: mvn allure:report

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
